### ISSUE TITLE
Ruby group capstone: set up Kanban board

### ISSUE THREAD

**Issue by eapenzacharias** [piero-vic/catalog-of-my-things#28]
# Ruby group capstone
[Kanban Board](https://github.com/piero-vic/catalog-of-my-things/projects/2)

Number Team members: 4

Team member 1 - [Piero](https://github.com/piero-vic)
Team member 2 - [Anibal](https://github.com/sj1978)
Team member 3 - [Eapen](https://github.com/eapenzacharias)
Team member 4 - [Amel](https://github.com/algerina)

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] what is intended with the "Create tasks on your Kanban board based on the project requirements divided by team member" is that every bullet point in the requirements divided by team member should have a separate card. for example when considering the below requirements for the group tasks there should be the following cards created:
- Create Item class
- define and set up constructor method  for item class properties
- add methods visible in diagram
- implement methods
- create a main.rb file
- Implement startup actions.

### Group task
- Create Item class in a separate .rb file.
- All Item class properties visible in the diagram should be defined and set up in the constructor method. _Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created._
- Add all methods visible in the diagram.
- Implement methods:
    - can_be_archived?() in the Item class
        - should return true if published_date is older than 10 years
        - otherwise, it should return false
    - move_to_archive() in the Item class
        - should reuse can_be_archived?() method
        - should change the archived property to true if the result of the can_be_archived?() method is true
        - should do nothing if the result of the can_be_archived?() method is false
 - Create a main.rb file that will serve as your console app entry-point.
 - Implement startup actions:
    - Present the user with a list of options to perform.
    - Let users choose an option.
    - If needed, ask for parameters for the option.
    - Have a way to quit the app.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🎉🍾✔**
Hello @mikethreels, @eapenzacharias, @algerina, @piero-vic, and @sj1978 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
